// ============================================
// AgentOffice - Default Agents Configuration (6 Specialist Agents)
// ============================================
import type { Agent } from '../types';

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: 'lead-engineer',
    name: 'Arka (Lead)',
    shortTag: 'LE',
    role: 'Lead Engineer',
    description: 'Memecah tugas, arsitektur, review, mendelegasikan ke agent lain.',
    avatar: { bodyColor: '#f59e0b', headColor: '#fbbf24', accentColor: '#fef3c7', icon: '👨‍💼' },
    systemPrompt: 'Kamu adalah Lead Engineer. Pecah tugas, rancang arsitektur, dan delegasikan.',
    modelConfig: { provider: 'anthropic', model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 4096 },
    skills: ['task-planning', 'system-architecture', 'code-review'],
    tools: ['task_planner', 'agent_router'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#f59e0b',
  },
  {
    id: 'ui-ux-designer',
    name: 'Reza (UI/UX)',
    shortTag: 'UI',
    role: 'UI/UX Designer',
    description: 'Wireframe, design system, review aksesibilitas.',
    avatar: { bodyColor: '#ec4899', headColor: '#f472b6', accentColor: '#fce7f3', icon: '🎨' },
    systemPrompt: 'Kamu adalah UI/UX Designer. Buat desain sistem, wireframe, dan periksa aksesibilitas.',
    modelConfig: { provider: 'openai', model: 'gpt-4o', temperature: 0.7, maxTokens: 4096 },
    skills: ['wireframing', 'design-system', 'accessibility-audit'],
    tools: ['grid_builder', 'color_harmonies'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#ec4899',
  },
  {
    id: 'frontend-dev',
    name: 'Fajar (FE)',
    shortTag: 'FE',
    role: 'Frontend Dev',
    description: 'Implementasi UI React/HTML/CSS, sandbox preview.',
    avatar: { bodyColor: '#10b981', headColor: '#34d399', accentColor: '#d1fae5', icon: '⚛️' },
    systemPrompt: 'Kamu adalah Frontend Developer. Implementasikan UI sesuai desain ke dalam kode React/CSS.',
    modelConfig: { provider: 'anthropic', model: 'claude-sonnet-4-20250514', temperature: 0.2, maxTokens: 8192 },
    skills: ['react-ts-dev', 'state-management', 'api-integration'],
    tools: ['ts_compiler', 'action_dispatcher'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#10b981',
  },
  {
    id: 'backend-dev',
    name: 'Dimas (BE)',
    shortTag: 'BE',
    role: 'Backend Dev',
    description: 'API, database, integrasi (REST/SQL, schema design).',
    avatar: { bodyColor: '#8b5cf6', headColor: '#a78bfa', accentColor: '#ede9fe', icon: '🗄️' },
    systemPrompt: 'Kamu adalah Backend Developer. Rancang API, kelola database, dan pastikan performa endpoint.',
    modelConfig: { provider: 'google', model: 'gemini-2.5-flash', temperature: 0.2, maxTokens: 4096 },
    skills: ['api-architecture', 'database-schema', 'query-optimization'],
    tools: ['migration_manager', 'sql_explainer'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#8b5cf6',
  },
  {
    id: 'debugger',
    name: 'Deni (Debug)',
    shortTag: 'DB',
    role: 'Debugger',
    description: 'Analisis error, reproduksi bug, saran fix.',
    avatar: { bodyColor: '#ef4444', headColor: '#f87171', accentColor: '#fecaca', icon: '🐛' },
    systemPrompt: 'Kamu adalah Debugger. Baca log error, temukan akar masalah, dan berikan solusi perbaikan.',
    modelConfig: { provider: 'anthropic', model: 'claude-sonnet-4-20250514', temperature: 0.2, maxTokens: 4096 },
    skills: ['runtime-debugger', 'root-cause'],
    tools: ['stack_analyzer', 'log_reader'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#ef4444',
  },
  {
    id: 'qa-tester',
    name: 'Qori (QA)',
    shortTag: 'QA',
    role: 'QA/Tester',
    description: 'Skenario & unit test.',
    avatar: { bodyColor: '#f97316', headColor: '#fb923c', accentColor: '#ffedd5', icon: '🧪' },
    systemPrompt: 'Kamu adalah QA/Tester. Pastikan kualitas kode dengan membuat skenario dan unit test menyeluruh.',
    modelConfig: { provider: 'google', model: 'gemini-2.5-flash', temperature: 0.2, maxTokens: 4096 },
    skills: ['unit-test-gen', 'scenario-planning'],
    tools: ['test_generator'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'work', color: '#f97316',
  },
  {
    id: 'product-manager',
    name: 'Tiara (PM)',
    shortTag: 'PM',
    role: 'Product Manager',
    description: 'PRD, user story, prioritas backlog.',
    avatar: { bodyColor: '#3b82f6', headColor: '#60a5fa', accentColor: '#dbeafe', icon: '👩‍💻' },
    systemPrompt: 'Kamu adalah Product Manager. Tulis PRD, buat user story, dan tentukan prioritas fitur.',
    modelConfig: { provider: 'openai', model: 'gpt-4o', temperature: 0.4, maxTokens: 4096 },
    skills: ['prd-scoping', 'user-story-mapping'],
    tools: ['prd_template', 'criteria_checklist'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'meeting', color: '#3b82f6',
  },
  {
    id: 'researcher',
    name: 'Risa (Riset)',
    shortTag: 'RS',
    role: 'Researcher',
    description: 'Riset web & ringkasan.',
    avatar: { bodyColor: '#0ea5e9', headColor: '#38bdf8', accentColor: '#e0f2fe', icon: '🔍' },
    systemPrompt: 'Kamu adalah Researcher. Cari data di internet, sintesis informasi, dan berikan insight akurat.',
    modelConfig: { provider: 'google', model: 'gemini-2.5-flash', temperature: 0.4, maxTokens: 4096 },
    skills: ['web-search', 'summarization'],
    tools: ['search_engine', 'content_scraper'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'break', color: '#0ea5e9',
  },
  {
    id: 'writer-docs',
    name: 'Gilang (Doc)',
    shortTag: 'WR',
    role: 'Writer/Docs',
    description: 'Dokumentasi, README, konten.',
    avatar: { bodyColor: '#14b8a6', headColor: '#2dd4bf', accentColor: '#ccfbf1', icon: '✍️' },
    systemPrompt: 'Kamu adalah Writer. Buat dokumentasi teknis, README interaktif, dan penulisan konten.',
    modelConfig: { provider: 'openai', model: 'gpt-4o-mini', temperature: 0.5, maxTokens: 4096 },
    skills: ['seo-copywriting', 'docs-generator'],
    tools: ['markdown_formatter'],
    status: 'idle', currentTaskSummary: 'Menunggu tugas', sessionStats: '0 ses', roomZone: 'break', color: '#14b8a6',
  }
];

export const PROVIDER_DEFAULTS = {
  anthropic: {
    name: 'Anthropic (Claude)',
    baseUrl: 'https://api.anthropic.com/v1',
    models: ['claude-sonnet-4-20250514', 'claude-3-5-haiku-20241022', 'claude-opus-4-20250514'],
  },
  google: {
    name: 'Google (Gemini)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.0-flash'],
  },
  openai: {
    name: 'OpenAI (GPT)',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o', 'gpt-4o-mini', 'o1-mini', 'o3-mini'],
  },
  'custom-openai': {
    name: 'Custom (OpenAI-compatible)',
    baseUrl: '',
    models: [],
  },
};
