// ============================================
// AgentOffice - Default Agents Configuration (6 Specialist Agents)
// ============================================
import type { Agent } from '../types';

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: 'arka-ao',
    name: 'Arka (AO)',
    shortTag: 'AO',
    role: 'Lead Architect & Agency Manager',
    description: 'Memecah tugas arsitektur, delegasi tim, dan review sprint.',
    avatar: {
      bodyColor: '#f59e0b',
      headColor: '#fbbf24',
      accentColor: '#fef3c7',
      icon: '👨‍💼',
    },
    systemPrompt: 'Kamu adalah Arka, Lead Architect dan Manager kantor. Analisis permintaan, dekomposisi subtugas, koordinasikan agen spesialis, dan awasi delivery.',
    modelConfig: {
      provider: 'anthropic',
      model: 'claude-sonnet-4-20250514',
      temperature: 0.3,
      maxTokens: 4096,
    },
    skills: ['task-planning', 'system-architecture', 'code-review', 'team-delegation', 'sprint-management'],
    tools: ['task_planner', 'adr_generator', 'diff_viewer', 'agent_router'],
    status: 'idle',
    currentTaskSummary: 'Draft • Rangkum laporan harian tim',
    sessionStats: '18 ses • 12.5rb tok • 84rb per hr',
    roomZone: 'work',
    color: '#f59e0b',
  },
  {
    id: 'tiara-pm',
    name: 'Tiara (PM)',
    shortTag: 'PM',
    role: 'Product Manager & Delivery',
    description: 'PRD scoping, user journey, prioritas backlog, dan timeline klien.',
    avatar: {
      bodyColor: '#3b82f6',
      headColor: '#60a5fa',
      accentColor: '#dbeafe',
      icon: '👩‍💻',
    },
    systemPrompt: 'Kamu adalah Tiara, Product Manager. Tangani PRD, user story, milestone, dan koordinasi kebutuhan klien.',
    modelConfig: {
      provider: 'openai',
      model: 'gpt-4o',
      temperature: 0.4,
      maxTokens: 4096,
    },
    skills: ['prd-scoping', 'client-coordination', 'user-story-mapping', 'deadline-tracking'],
    tools: ['prd_template', 'brief_analyzer', 'criteria_checklist'],
    status: 'idle',
    currentTaskSummary: 'PM#1 • Tambah filter tanggal di dashboard',
    sessionStats: '12 ses • 8.1rb tok • 62rb per hr',
    roomZone: 'meeting',
    color: '#3b82f6',
  },
  {
    id: 'fajar-fe',
    name: 'Fajar (FE)',
    shortTag: 'FE',
    role: 'Frontend Developer & 3D Web',
    description: 'Implementasi UI React 19, visualisasi Three.js, dan responsive layouts.',
    avatar: {
      bodyColor: '#10b981',
      headColor: '#34d399',
      accentColor: '#d1fae5',
      icon: '⚛️',
    },
    systemPrompt: 'Kamu adalah Fajar, Senior Frontend Developer. Bangun komponen React fungsional, integrasikan 3D Three.js, dan kelola state reaktif.',
    modelConfig: {
      provider: 'anthropic',
      model: 'claude-sonnet-4-20250514',
      temperature: 0.2,
      maxTokens: 8192,
    },
    skills: ['react-ts-dev', 'threejs-graphics', 'state-management', 'api-integration'],
    tools: ['ts_compiler', 'three_inspector', 'action_dispatcher', 'stream_reader'],
    status: 'idle',
    currentTaskSummary: 'FE#2 • Cek komponen form landing page',
    sessionStats: '22 ses • 14.8rb tok • 105rb per hr',
    roomZone: 'work',
    color: '#10b981',
  },
  {
    id: 'dimas-de',
    name: 'Dimas (DE)',
    shortTag: 'DE',
    role: 'Backend & Database Engineer',
    description: 'Arsitektur REST API, skema SQLite/Postgres, query tuning, dan security.',
    avatar: {
      bodyColor: '#8b5cf6',
      headColor: '#a78bfa',
      accentColor: '#ede9fe',
      icon: '🗄️',
    },
    systemPrompt: 'Kamu adalah Dimas, Backend Engineer. Rancang endpoint API andal, optimalkan query SQL, dan pastikan keamanan basis data.',
    modelConfig: {
      provider: 'google',
      model: 'gemini-2.5-flash',
      temperature: 0.2,
      maxTokens: 4096,
    },
    skills: ['api-architecture', 'database-schema', 'query-optimization', 'security-audit'],
    tools: ['postman_runner', 'migration_manager', 'sql_explainer'],
    status: 'idle',
    currentTaskSummary: 'Web/Arch • Cek halaman katalog produk',
    sessionStats: '15 ses • 11.2rb tok • 78rb per hr',
    roomZone: 'work',
    color: '#8b5cf6',
  },
  {
    id: 'reza-sm',
    name: 'Reza (SM)',
    shortTag: 'SM',
    role: 'SEO & Content Designer',
    description: 'Wireframing interaktif, design system tokens, aset visual media sosial.',
    avatar: {
      bodyColor: '#ec4899',
      headColor: '#f472b6',
      accentColor: '#fce7f3',
      icon: '🎨',
    },
    systemPrompt: 'Kamu adalah Reza, UI/UX & Content Designer. Buat wireframe layout, palet warna cyberpunk modern, dan visual viral campaign.',
    modelConfig: {
      provider: 'openai',
      model: 'gpt-4o',
      temperature: 0.7,
      maxTokens: 4096,
    },
    skills: ['wireframing', 'design-system', 'accessibility-audit', 'social-media-assets'],
    tools: ['grid_builder', 'color_harmonies', 'contrast_checker', 'aspect_ratio_cropper'],
    status: 'idle',
    currentTaskSummary: 'Hero-ads • Tarik performa iklan minggu ini',
    sessionStats: '11 ses • 7.4rb tok • 55rb per hr',
    roomZone: 'work',
    color: '#ec4899',
  },
  {
    id: 'gilang-cw',
    name: 'Gilang (CW)',
    shortTag: 'CW',
    role: 'Content Writer & QA Tester',
    description: 'Copywriting konversi, penulisan artikel SEO, testing unit, dan dokumentasi.',
    avatar: {
      bodyColor: '#06b6d4',
      headColor: '#22d3ee',
      accentColor: '#cffafe',
      icon: '✍️',
    },
    systemPrompt: 'Kamu adalah Gilang, Content Writer dan QA. Tulis copy memikat, buat pengujian automated unit test, dan audit error stack trace.',
    modelConfig: {
      provider: 'google',
      model: 'gemini-2.5-flash',
      temperature: 0.3,
      maxTokens: 4096,
    },
    skills: ['seo-copywriting', 'docs-generator', 'runtime-debugger', 'unit-test-gen'],
    tools: ['keyword_density', 'stack_analyzer', 'test_generator', 'markdown_formatter'],
    status: 'idle',
    currentTaskSummary: 'Docs • Tulis draf artikel SEO',
    sessionStats: '14 ses • 9.8rb tok • 68rb per hr',
    roomZone: 'break',
    color: '#06b6d4',
  },
];

export const PROVIDER_DEFAULTS = {
  anthropic: {
    name: 'Anthropic (Claude)',
    baseUrl: 'https://api.anthropic.com/v1',
    models: ['claude-sonnet-4-20250514', 'claude-3-5-haiku-20241022', 'claude-opus-4-20250514'],
  },
  google: {
    name: 'Google (Gemini)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.0-flash'],
  },
  openai: {
    name: 'OpenAI (GPT)',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o', 'gpt-4o-mini', 'o1-mini', 'o3-mini'],
  },
  'custom-openai': {
    name: 'Custom (OpenAI-compatible)',
    baseUrl: '',
    models: [],
  },
};
